import { createClient } from "https://esm.sh/@supabase/supabase-js@2.45.4";
import Stripe from "https://esm.sh/stripe@14.21.0?target=deno";
const stripe=new Stripe(Deno.env.get("STRIPE_SECRET_KEY"),{apiVersion:"2024-06-20",httpClient:Stripe.createFetchHttpClient()});
const WH=Deno.env.get("STRIPE_WEBHOOK_SECRET");
const supabase=createClient(Deno.env.get("SUPABASE_URL"),Deno.env.get("SUPABASE_SERVICE_ROLE_KEY"));
const P2P={"price_1TBNx6E9lvvsgykljqvbHkNt":"starter","price_1TBNx9E9lvvsgyklTfsIiHGQ":"viral","price_1TBNxCE9lvvsgyklJwtWCfHP":"agency","price_1TAy8IE9lvvsgyklJcwJqexj":"starter","price_1TAy8LE9lvvsgyklL8xTh2sX":"viral","price_1TAy8PE9lvvsgyklmJmPkzfb":"agency","price_1T9d6KE9lvvsgyklY0a9A9pw":"starter","price_1T9d6OE9lvvsgykl1B8afnaJ":"viral","price_1T9d6TE9lvvsgykltb5DtnyE":"agency"};
const ADDONS={"price_1TBNxeE9lvvsgyklaQbyEvOg":{videoSeconds:60},"price_1TBNxhE9lvvsgyklh6cbC8NV":{videoSeconds:180},"price_1TBNxlE9lvvsgyklSgVMQdY2":{captionCredits:25},"price_1TBNxnE9lvvsgyklWqYQQbPh":{captionCredits:100}};
function getPeriod(){const d=new Date();return d.getUTCFullYear()+"-"+String(d.getUTCMonth()+1).padStart(2,"0");}
async function upsertSub(d){await supabase.from("subscriptions").upsert({stripe_customer_id:d.cid,stripe_subscription_id:d.sid,plan:d.plan,status:d.status,current_period_start:new Date(d.ps*1000).toISOString(),current_period_end:new Date(d.pe*1000).toISOString(),cancel_at_period_end:d.cape,canceled_at:d.ca?new Date(d.ca*1000).toISOString():null,updated_at:new Date().toISOString(),...(d.uid?{supabase_user_id:d.uid}:{})},{onConflict:"stripe_subscription_id"});}
async function getUID(cid){const{data}=await supabase.from("subscriptions").select("supabase_user_id").eq("stripe_customer_id",cid).maybeSingle();if(data?.supabase_user_id)return data.supabase_user_id;try{const c=await stripe.customers.retrieve(cid);if(c.email){const{data:users}=await supabase.auth.admin.listUsers();return users?.users?.find(u=>u.email===c.email)?.id;}}catch(e){console.error(e);}return undefined;}
async function creditAddon(uid,priceId){const a=ADDONS[priceId];if(!a)return;const p=getPeriod();await supabase.from("usage_tracking").upsert({supabase_user_id:uid,period:p,ai_analyses_used:0,posts_scheduled:0,video_seconds_used:0,video_seconds_bonus:0,caption_credits_bonus:0},{onConflict:"supabase_user_id,period",ignoreDuplicates:true});if(a.videoSeconds)await supabase.rpc("increment_video_seconds_bonus",{p_user_id:uid,p_period:p,p_seconds:a.videoSeconds});if(a.captionCredits)await supabase.rpc("increment_caption_credits_bonus",{p_user_id:uid,p_period:p,p_credits:a.captionCredits});}
async function commission(inv,uid){const{data:ref}=await supabase.from("referrals").select("id,referrer_user_id").eq("referred_user_id",uid).eq("status","active").maybeSingle();if(!ref)return;const{data:rs}=await supabase.from("subscriptions").select("status,stripe_customer_id").eq("supabase_user_id",ref.referrer_user_id).maybeSingle();if(rs?.status!=="active"&&!rs?.stripe_customer_id?.startsWith("promo_"))return;const{data:ex}=await supabase.from("referral_commissions").select("id").eq("stripe_invoice_id",inv.id).maybeSingle();if(ex)return;const c=Math.floor((inv.amount_paid??0)*0.20);if(c<=0)return;await supabase.from("referral_commissions").insert({referral_id:ref.id,referrer_user_id:ref.referrer_user_id,amount_cents:c,stripe_invoice_id:inv.id,status:"pending",period_start:inv.period_start?new Date(inv.period_start*1000).toISOString():null});}
Deno.serve(async(req)=>{
  if(req.method!=="POST")return new Response("Method not allowed",{status:405});
  const sig=req.headers.get("stripe-signature");if(!sig)return new Response("Missing signature",{status:400});
  const body=await req.arrayBuffer();let event;
  try{event=await stripe.webhooks.constructEventAsync(new TextDecoder().decode(body),sig,WH);}catch(e){return new Response("Webhook error: "+e.message,{status:400});}
  try{
    switch(event.type){
      case"customer.subscription.created":case"customer.subscription.updated":{const s=event.data.object;const pid=s.items.data[0]?.price?.id??"";const uid=await getUID(s.customer);await upsertSub({cid:s.customer,sid:s.id,plan:P2P[pid]??"unknown",status:s.status,ps:s.current_period_start,pe:s.current_period_end,cape:s.cancel_at_period_end,ca:s.canceled_at??null,uid});if(s.status==="active"&&uid)await supabase.from("referrals").update({status:"active",activated_at:new Date().toISOString()}).eq("referred_user_id",uid).eq("status","pending");break;}
      case"customer.subscription.deleted":{const s=event.data.object;const pid=s.items.data[0]?.price?.id??"";const uid=await getUID(s.customer);await upsertSub({cid:s.customer,sid:s.id,plan:P2P[pid]??"unknown",status:"canceled",ps:s.current_period_start,pe:s.current_period_end,cape:s.cancel_at_period_end,ca:s.canceled_at??Math.floor(Date.now()/1000),uid});if(uid)await supabase.from("referrals").update({status:"cancelled"}).eq("referred_user_id",uid);break;}
      case"invoice.payment_succeeded":{const inv=event.data.object;if(inv.customer&&inv.amount_paid>0){const uid=await getUID(inv.customer);if(uid)await commission(inv,uid);}break;}
      case"invoice.payment_failed":{const inv=event.data.object;if(inv.subscription)await supabase.from("subscriptions").update({status:"past_due",updated_at:new Date().toISOString()}).eq("stripe_subscription_id",inv.subscription);break;}
      case"checkout.session.completed":{const s=event.data.object;const uid=s.metadata?.supabase_user_id;const cid=s.customer;if(uid&&cid){await supabase.from("subscriptions").upsert({stripe_customer_id:cid,supabase_user_id:uid,updated_at:new Date().toISOString()},{onConflict:"stripe_customer_id"});if(s.mode==="payment"&&s.metadata?.addon_type){try{const li=await stripe.checkout.sessions.listLineItems(s.id);const pid=li.data[0]?.price?.id;if(pid)await creditAddon(uid,pid);}catch(e){console.error("Addon credit failed:",e);}}}break;}
    }
  }catch(e){console.error("Handler error:",e.message);return new Response("Handler error",{status:500});}
  return new Response(JSON.stringify({received:true}),{headers:{"Content-Type":"application/json"}});
});
